server.port=${PORT:8080}
spring.mongodb.uri=mongodb+srv://nithish:9842143808@bankingsystem.osetvbz.mongodb.net/bankingdb?retryWrites=true&w=majority&appName=Bankingsystem
spring.mongodb.auto-index-creation=true