server.port=${PORT:8080}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://nithish:9842143808@bankingsystem.osetvbz.mongodb.net/bankingdb?retryWrites=true&w=majority&appName=Bankingsystem}
spring.data.mongodb.auto-index-creation=true
