spring.application.name=kanban-manager

spring.data.mongodb.uri=mongodb+srv://nithish:9842143808@taskmanager.iwcvmdk.mongodb.net/kanban_db?appName=taskmanager
server.port=8080
app.jwt.secret=myVerySecretKeyForJwtAuthentication123456789
app.jwt.expiration-ms=86400000